deeplogic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pdf.urls'))
]

urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

pdf/urls.py
from django.urls import path
from django.views.generic.edit import CreateView
from django.contrib import admin
from . import views

app_name = 'pdf'

urlpatterns = [
    path('', views.LoginView.as_view() , name='login'),
    path('login/', views.LoginView.as_view() , name='login'),
    path('register/', views.RegisterView.as_view() , name='register'),
    path('logout/', views.LogoutView.as_view() , name='logout'),

    path('home/', views.IndexView.as_view(), name='index'),
    path('list', views.TextListView.as_view(), name='list'),
    path('detail/<pk>', views.TextDetailView.as_view() , name='detail'),



    
]

pdf/models.py
from django.db import models

# Create your models here.
class Text(models.Model):

    __tablename__ = 'Text'

    filename = models.CharField(max_length=80)
    text = models.TextField()
    file_path = models.CharField(max_length=100, blank=True, null=True)
    
    def __str__(self):
        return self.filename

pdf/forms.py
from django import forms
from django.core.exceptions import RequestAborted, ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import widgets
from django.utils.translation import gettext_lazy as _
from django.conf import settings    
from django.http import HttpResponse, HttpResponseRedirect, request
from django.core.mail import send_mail


from pdf.models import Text

class TextForm(forms.Form):

    file = forms.FileField()  

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user



   

pdf/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, FormView, UpdateView
from django.views.generic import TemplateView
from .models import Text
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .forms import TextForm, NewUserForm
from django.core.files.storage import FileSystemStorage
from django.contrib.auth import login, authenticate , logout
from django.contrib import messages
from django.shortcuts import  render, redirect
from django.contrib.auth.forms import AuthenticationForm #add this
import io
from nanonets import NANONETSOCR
import environ
env = environ.Env()
environ.Env.read_env

# Create your views here.
      
class IndexView(FormView):
    template_name = 'pdf/index.html'
    form_class = TextForm
    context_object_name = "pdf_context"
    
    def get_queryset(self):
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        self.pdf_context = super().get_context_data(**kwargs)

        self.pdf_context['form'] = self.form_class
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs ):

        file = request.FILES['file']
        # print(file.read(), file=log_file)
        fs = FileSystemStorage()
        filename = fs.save(file.name, file)
        uploaded_file_url = fs.url(filename)[1:]
        # print(uploaded_file_url)
        model = NANONETSOCR()
        model.set_token("XQmXfZT6exouQq4zDoRSVsR3cuMVt6g1")
        file_path = r"C:\Users\User\OneDrive\Desktop\sterl\wellfound\deeplogic" + "/" + uploaded_file_url
        string = model.convert_to_string(file_path,formatting='lines and spaces') 

        # print(string)
        # print(file_path)

        new_text = Text.objects.create(text=string, filename=file.name, file_path=uploaded_file_url)
        new_text.save()
        # print(new_text.pk)

        # return render(request, self.template_name, {'form': self.form_class})
        return redirect('pdf:detail', pk=new_text.id)


class TextListView(ListView):
    model = Text
    context_object_name = 'pdf_context'
    template_name='pdf/list.html'

    def get_queryset(self):
        return Text.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    

class TextDetailView(DetailView):
    model = Text
    template_name='pdf/detail.html'
    context_object_name = 'pdf_context'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
        

class RegisterView(TemplateView):
    
    template_name = 'pdf/registration/register.html'
    context_object_name = 'signup_context'
    form_class = NewUserForm()

    def get_context_data(self, **kwargs):
        self.signup_context = super().get_context_data(**kwargs)
        self.signup_context['register_form'] = self.form_class
        return self.signup_context

    def post(self, request, *args, **kwargs ):
        form = NewUserForm(request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect("pdf:index")
        else:
            messages.error(request, "Unsuccessful registration. Invalid information.")
        form = NewUserForm()
        return render (request=request, template_name="pdf/registration/register.html", context={"register_form":form})




class LoginView(TemplateView):
    template_name = 'pdf/registration/login.html'
    form_class = AuthenticationForm()
    context_object_name = "login_context"

    def get_context_data(self, **kwargs):
        self.login_context = super().get_context_data(**kwargs)
        self.login_context['login_form'] = self.form_class

        return self.login_context

    def post(self, request, *args, **kwargs):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("pdf:index")
            else:
                messages.error(request,"Invalid username or password.")
        else:
            messages.error(request,"Invalid username or password.")
        form = AuthenticationForm()
        return render(request=request, template_name="pdf/registration/login.html", context={"login_form":form})



class LogoutView(ListView):
    
    def get(self,request):

        logout(request)
        return redirect("pdf:login")

pdf/templates/pdf/detail.html
{% extends 'pdf/layout.html' %}
{% load static %}
{% get_media_prefix %}

{% block content %}
<div class= 'container py-2'>
          {% if pdf_context %}
          <div class='row align-items-start justify-content-center'>
             
           <div class='col-sm-10'>
            <h1>{{ pdf_context.filename }} </h1>
            <a href="/{{ BASE_DIR}}{{ pdf_context.file_path }}" width=90%, height=90%
                >Go to file</a>
            <p class='mb-4'>{{ pdf_context.text | linebreaks | safe}}</p>
                   
           </div>
          </div>
              {% comment %} <li>
                <p>{{ pdf_context.text | linebreaksbr | safe}}</p>
                <a href="/{{ BASE_DIR}}{{ pdf_context.file_path }}" width=90%, height=90%
                >Go to file</a>
              </li> {% endcomment %}
          </ul>
          {% else %}
            <p>There are no pdfs yet in the library.</p>
          {% endif %}

</div>
{% endblock %}

pdf/templates/pdf/index.html
{% extends 'pdf/layout.html' %}
{% load static %}

{% block content %}
<div class= 'container-fluid py-5 '>
   <div class='row align-items-center justify-content-center py-5 '>
        <div class="col-sm-6 main_form py-5" style="background-color: white;">
            <form class='form py-5' method="post"  enctype="multipart/form-data" style="margin-left: 5px; border: 1px solid  rgb(41, 36, 92); padding: 8%;">
                {% csrf_token %}
            {% load crispy_forms_tags %}
            {{ form|crispy }}
    
            <input type="submit" value="Submit" class="btn btn-success mt-2">
            </form>
        </div>
   </div>
</div>
{% endblock %}

pdf/templates/pdf/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'pdf/index.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>

    <title>PDF-Deeplogic</title>
</head>
<body class="">
  {% block nav %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-nav" style="background-color:rgb(86, 40, 9)">
    <a class="navbar-brand" href="{% url 'pdf:index' %}">PDF Uploader</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" 
    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText" style="width: auto;">
      <ul class="navbar-nav mr-auto" style="width: auto;">
        
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'pdf:index' %}">Add File<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'pdf:list' %}">My Files</a>
          </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'pdf:logout' %}">Sign Out</a>
        </li>
      
    </ul>
        
    
      <span class="navbar-text" style=" width: auto; color: white;">
        <!-- <a  style="width: auto;" class="">&nbsp;Welcome, {{ user.username | capfirst }}</a> -->
      </span>
      <span class="nav-item" style="">
      </span>

    
    
    </div>
  </nav>
    {% endblock %}
    {% block content %}
    {% endblock %}
</body>
</html>

pdf/templates/pdf/list.html
{% extends 'pdf/layout.html' %}
{% load static %}

{% block content %}
<div class= 'container-fluid '>
    <div class='row align-items-center justify-content-center py-5 my-5'>
  <div class='col-sm-10 text-left'>
      <h1 class='font=weight-bold'>Uploaded Files</h1>
      {% if pdf_context %}
      <ul style="list-style-type: none";>
        <div class='row align-items-center justify-content-center my-5 py-5 tex-dark w-100'>

   
        {% for pdf in pdf_context %}

          <div class='col-sm-3 py-5 border border-white align-self-center brand_color_blur'>
              <li style="list-style-type: none";>
                <a href="{% url 'pdf:detail' pdf.id %}"  > {{ pdf.filename }} </a>
              </li>
          </div>
        {% endfor %}

    </div>
      </ul>
      {% else %}
        <p>There are no pdfs yet in the library.</p>
      {% endif %}
  </div>
</div>
</div>
{% endblock %}